export enum AreaSocial {
    GENERAL = 'GENERAL',
    AREA_INVENTRIOS = 'AREA_INVENTRIOS',
    AREA_REPORTES = 'AREA_REPORTES',
    AREA_VENTAS = 'AREA_VENTAS',
    AREA_PERSONAL = 'AREA_PERSONAL',
  }